repos:
-   repo: https://github.com/python-poetry/poetry
    rev: 1.6.1
    hooks:
    -   id: poetry-check
        args: ["-C", "./src"]
    -   id: poetry-lock
        args: ["-C", "./src", "--no-update"]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.5
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: poetry -C src run pytest src
        language: system
        types: [python]
        require_serial: true
        pass_filenames: false

