---
name: CD

on:
  workflow_call: # yamllint disable-line rule:truthy
    inputs:
      version:
        description: 'The version of the package'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    environment:
      name: pypi
      url: https://pypi.org/p/data-factory-testing-framework
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Download sdist
        uses: actions/download-artifact@v4.1.7
        with:
          name: sdist
          path: dist
      - name: Download whl
        uses: actions/download-artifact@v4.1.7
        with:
          name: whl
          path: dist
      - name: Create release
        run: gh release create "v${{ inputs.version }}" --prerelease --target ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./dist
