---
name: CI-CD

on: [push]  # yamllint disable-line rule:truthy

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  cd:
    needs: [ci]
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
    uses: ./.github/workflows/cd.yml
    with:
      version: ${{ needs.ci.outputs.version }}
