---
name: CD

on:
  workflow_call: # yamllint disable-line rule:truthy
    inputs:
      os:
        description: 'Operating system'
        required: true
        type: string
      python-version:
        description: 'Python version'
        required: true
        type: string
      dotnet-version:
        description: '.NET version'
        required: true
        type: string
      dist:
        description: 'Distribution artifact'
        required: true
        type: string

jobs:
  e2e:
    runs-on: ${{ inputs.os }}
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
      - name: Download dist
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.dist }}
          path: dist
      - name: Install pytest
        run: python -m pip install pytest
      - name: Install project
        run: pip install $(ls)
        working-directory: dist
      - name: Run end-to-end tests
        run: python -m pytest examples
